// This file was generated by generate.py

#include "Metadata.h"

static const char* const names[] = {
    "Serial Number",
    "Calibration Date",
    "Offset",
    "Sensitivity",
    "Firmware Version",
    "Device Name",
    "Serial Enabled",
    "Serial Baud Rate",
    "Serial RTS/CTS Enabled",
};

static const char* const keys[] = {
    "serial_number",
    "calibration_date",
    "offset",
    "sensitivity",
    "firmware_version",
    "device_name",
    "serial_enabled",
    "serial_baud_rate",
    "serial_rts_cts_enabled",
};

const MetadataType types[] = {
    MetadataTypeCharArray,
    MetadataTypeCharArray,
    MetadataTypeFloat,
    MetadataTypeFloat,
    MetadataTypeCharArray,
    MetadataTypeCharArray,
    MetadataTypeBool,
    MetadataTypeUint32,
    MetadataTypeBool,
};

const size_t sizes[] = {
    sizeof (((Ximu3SettingsValues *) 0)->serialNumber),
    sizeof (((Ximu3SettingsValues *) 0)->calibrationDate),
    sizeof (((Ximu3SettingsValues *) 0)->offset),
    sizeof (((Ximu3SettingsValues *) 0)->sensitivity),
    sizeof (((Ximu3SettingsValues *) 0)->firmwareVersion),
    sizeof (((Ximu3SettingsValues *) 0)->deviceName),
    sizeof (((Ximu3SettingsValues *) 0)->serialEnabled),
    sizeof (((Ximu3SettingsValues *) 0)->serialBaudRate),
    sizeof (((Ximu3SettingsValues *) 0)->serialRtsCtsEnabled),
};

const void* const defaults[] = {
    (void*) (&(char[16]) {"Unknown"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(float) {0.0f}),
    (void*) (&(float) {1.0f}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Twintig"}),
    (void*) (&(bool) {true}),
    (void*) (&(uint32_t) {3000000}),
    (void*) (&(bool) {false}),
};

const bool preserveds[] = {
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
};

const bool readOnlys[] = {
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
};

static void* GetValue(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {
    switch (index) {
        case Ximu3SettingsIndexSerialNumber:
            return &settings->values.serialNumber;
        case Ximu3SettingsIndexCalibrationDate:
            return &settings->values.calibrationDate;
        case Ximu3SettingsIndexOffset:
            return &settings->values.offset;
        case Ximu3SettingsIndexSensitivity:
            return &settings->values.sensitivity;
        case Ximu3SettingsIndexFirmwareVersion:
            return &settings->values.firmwareVersion;
        case Ximu3SettingsIndexDeviceName:
            return &settings->values.deviceName;
        case Ximu3SettingsIndexSerialEnabled:
            return &settings->values.serialEnabled;
        case Ximu3SettingsIndexSerialBaudRate:
            return &settings->values.serialBaudRate;
        case Ximu3SettingsIndexSerialRtsCtsEnabled:
            return &settings->values.serialRtsCtsEnabled;

    }
    return NULL; // avoid compiler warning
}

Metadata MetadataGet(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {
    const Metadata metaData = {
        .name = names[index],
        .key = keys[index],
        .value = GetValue(settings, index),
        .type = types[index],
        .size = sizes[index],
        .defaultValue = defaults[index],
        .preserved = preserveds[index],
        .readOnly = readOnlys[index],
        .applied = &settings->applied[index],
    };
    return metaData;
}
