// This file was generated by generate.py

#include "Metadata.h"

static const char* const names[] = {
    "Calibration Date",
    "Gyroscope Misalignment",
    "Gyroscope Sensitivity",
    "Gyroscope Offset",
    "Accelerometer Misalignment",
    "Accelerometer Sensitivity",
    "Accelerometer Offset",
    "Soft-iron Matrix",
    "Hard-iron Offset",
    "Model",
    "Serial Number",
    "Hardware Version",
    "Bootloader Version",
    "Firmware Version",
    "Device Name",
    "Serial Enabled",
    "Serial Baud Rate",
    "Serial RTS/CTS Enabled",
    "Gyroscope Notch Filter Enabled",
    "Gyroscope Anti-aliasing",
    "Accelerometer Anti-aliasing",
    "Sample Rate",
    "Axes Remap",
    "Gyroscope Bias Correction Enabled",
    "AHRS Update Rate Divisor",
    "AHRS Axes Convention",
    "AHRS Gain",
    "AHRS Acceleration Rejection",
    "Data Message Mode",
    "AHRS Message Type",
    "Inertial Message Rate Divisor",
    "AHRS Message Rate Divisor",
    "Temperature Message Rate Divisor",
    "USB Send Mode",
    "Serial Send Mode",
};

static const char* const keys[] = {
    "calibration_date",
    "gyroscope_misalignment",
    "gyroscope_sensitivity",
    "gyroscope_offset",
    "accelerometer_misalignment",
    "accelerometer_sensitivity",
    "accelerometer_offset",
    "soft_iron_matrix",
    "hard_iron_offset",
    "model",
    "serial_number",
    "hardware_version",
    "bootloader_version",
    "firmware_version",
    "device_name",
    "serial_enabled",
    "serial_baud_rate",
    "serial_rts_cts_enabled",
    "gyroscope_notch_filter_enabled",
    "gyroscope_anti_aliasing",
    "accelerometer_anti_aliasing",
    "sample_rate",
    "axes_remap",
    "gyroscope_bias_correction_enabled",
    "ahrs_update_rate_divisor",
    "ahrs_axes_convention",
    "ahrs_gain",
    "ahrs_acceleration_rejection",
    "data_message_mode",
    "ahrs_message_type",
    "inertial_message_rate_divisor",
    "ahrs_message_rate_divisor",
    "temperature_message_rate_divisor",
    "usb_send_mode",
    "serial_send_mode",
};

const MetadataType types[] = {
    MetadataTypeString,
    MetadataTypeFusionMatrix,
    MetadataTypeFusionVector,
    MetadataTypeFusionVector,
    MetadataTypeFusionMatrix,
    MetadataTypeFusionVector,
    MetadataTypeFusionVector,
    MetadataTypeFusionMatrix,
    MetadataTypeFusionVector,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeBool,
    MetadataTypeUint32,
    MetadataTypeBool,
    MetadataTypeBool,
    MetadataTypeIcmAntiAliasing,
    MetadataTypeIcmAntiAliasing,
    MetadataTypeIcmSampleRate,
    MetadataTypeFusionRemapAlignment,
    MetadataTypeBool,
    MetadataTypeUint32,
    MetadataTypeFusionConvention,
    MetadataTypeFloat,
    MetadataTypeFloat,
    MetadataTypeSendDataMessageMode,
    MetadataTypeSendAhrsMessageType,
    MetadataTypeUint32,
    MetadataTypeUint32,
    MetadataTypeUint32,
    MetadataTypeSendInterfaceMode,
    MetadataTypeSendInterfaceMode,
};

const size_t sizes[] = {
    sizeof (((Ximu3SettingsValues *) 0)->calibrationDate),
    sizeof (((Ximu3SettingsValues *) 0)->gyroscopeMisalignment),
    sizeof (((Ximu3SettingsValues *) 0)->gyroscopeSensitivity),
    sizeof (((Ximu3SettingsValues *) 0)->gyroscopeOffset),
    sizeof (((Ximu3SettingsValues *) 0)->accelerometerMisalignment),
    sizeof (((Ximu3SettingsValues *) 0)->accelerometerSensitivity),
    sizeof (((Ximu3SettingsValues *) 0)->accelerometerOffset),
    sizeof (((Ximu3SettingsValues *) 0)->softIronMatrix),
    sizeof (((Ximu3SettingsValues *) 0)->hardIronOffset),
    sizeof (((Ximu3SettingsValues *) 0)->model),
    sizeof (((Ximu3SettingsValues *) 0)->serialNumber),
    sizeof (((Ximu3SettingsValues *) 0)->hardwareVersion),
    sizeof (((Ximu3SettingsValues *) 0)->bootloaderVersion),
    sizeof (((Ximu3SettingsValues *) 0)->firmwareVersion),
    sizeof (((Ximu3SettingsValues *) 0)->deviceName),
    sizeof (((Ximu3SettingsValues *) 0)->serialEnabled),
    sizeof (((Ximu3SettingsValues *) 0)->serialBaudRate),
    sizeof (((Ximu3SettingsValues *) 0)->serialRtsCtsEnabled),
    sizeof (((Ximu3SettingsValues *) 0)->gyroscopeNotchFilterEnabled),
    sizeof (((Ximu3SettingsValues *) 0)->gyroscopeAntiAliasing),
    sizeof (((Ximu3SettingsValues *) 0)->accelerometerAntiAliasing),
    sizeof (((Ximu3SettingsValues *) 0)->sampleRate),
    sizeof (((Ximu3SettingsValues *) 0)->axesRemap),
    sizeof (((Ximu3SettingsValues *) 0)->gyroscopeBiasCorrectionEnabled),
    sizeof (((Ximu3SettingsValues *) 0)->ahrsUpdateRateDivisor),
    sizeof (((Ximu3SettingsValues *) 0)->ahrsAxesConvention),
    sizeof (((Ximu3SettingsValues *) 0)->ahrsGain),
    sizeof (((Ximu3SettingsValues *) 0)->ahrsAccelerationRejection),
    sizeof (((Ximu3SettingsValues *) 0)->dataMessageMode),
    sizeof (((Ximu3SettingsValues *) 0)->ahrsMessageType),
    sizeof (((Ximu3SettingsValues *) 0)->inertialMessageRateDivisor),
    sizeof (((Ximu3SettingsValues *) 0)->ahrsMessageRateDivisor),
    sizeof (((Ximu3SettingsValues *) 0)->temperatureMessageRateDivisor),
    sizeof (((Ximu3SettingsValues *) 0)->usbSendMode),
    sizeof (((Ximu3SettingsValues *) 0)->serialSendMode),
};

const void* const defaults[] = {
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(FusionMatrix) {{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}}),
    (void*) (&(FusionVector) {{1.0f, 1.0f, 1.0f}}),
    (void*) (&(FusionVector) {{0.0f, 0.0f, 0.0f}}),
    (void*) (&(FusionMatrix) {{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}}),
    (void*) (&(FusionVector) {{1.0f, 1.0f, 1.0f}}),
    (void*) (&(FusionVector) {{0.0f, 0.0f, 0.0f}}),
    (void*) (&(FusionMatrix) {{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}}),
    (void*) (&(FusionVector) {{0.0f, 0.0f, 0.0f}}),
    (void*) (&(char[32]) {"Twintig"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Twintig"}),
    (void*) (&(bool) {true}),
    (void*) (&(uint32_t) {115200}),
    (void*) (&(bool) {false}),
    (void*) (&(bool) {true}),
    (void*) (&(IcmAntiAliasing) {IcmAntiAliasing42Hz}),
    (void*) (&(IcmAntiAliasing) {IcmAntiAliasing42Hz}),
    (void*) (&(IcmSampleRate) {IcmSampleRate100Hz}),
    (void*) (&(FusionRemapAlignment) {FusionRemapAlignmentPXPYPZ}),
    (void*) (&(bool) {false}),
    (void*) (&(uint32_t) {1}),
    (void*) (&(FusionConvention) {FusionConventionNwu}),
    (void*) (&(float) {0.5f}),
    (void*) (&(float) {10.0f}),
    (void*) (&(SendDataMessageMode) {SendDataMessageModeBinary}),
    (void*) (&(SendAhrsMessageType) {SendAhrsMessageTypeQuaternion}),
    (void*) (&(uint32_t) {1}),
    (void*) (&(uint32_t) {1}),
    (void*) (&(uint32_t) {0}),
    (void*) (&(SendInterfaceMode) {SendInterfaceModeBlocking}),
    (void*) (&(SendInterfaceMode) {SendInterfaceModeDisabled}),
};

const bool preserveds[] = {
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
};

const bool readOnlys[] = {
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
};

static void* GetValue(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {
    switch (index) {
        case Ximu3SettingsIndexCalibrationDate:
            return &settings->values.calibrationDate;
        case Ximu3SettingsIndexGyroscopeMisalignment:
            return &settings->values.gyroscopeMisalignment;
        case Ximu3SettingsIndexGyroscopeSensitivity:
            return &settings->values.gyroscopeSensitivity;
        case Ximu3SettingsIndexGyroscopeOffset:
            return &settings->values.gyroscopeOffset;
        case Ximu3SettingsIndexAccelerometerMisalignment:
            return &settings->values.accelerometerMisalignment;
        case Ximu3SettingsIndexAccelerometerSensitivity:
            return &settings->values.accelerometerSensitivity;
        case Ximu3SettingsIndexAccelerometerOffset:
            return &settings->values.accelerometerOffset;
        case Ximu3SettingsIndexSoftIronMatrix:
            return &settings->values.softIronMatrix;
        case Ximu3SettingsIndexHardIronOffset:
            return &settings->values.hardIronOffset;
        case Ximu3SettingsIndexModel:
            return &settings->values.model;
        case Ximu3SettingsIndexSerialNumber:
            return &settings->values.serialNumber;
        case Ximu3SettingsIndexHardwareVersion:
            return &settings->values.hardwareVersion;
        case Ximu3SettingsIndexBootloaderVersion:
            return &settings->values.bootloaderVersion;
        case Ximu3SettingsIndexFirmwareVersion:
            return &settings->values.firmwareVersion;
        case Ximu3SettingsIndexDeviceName:
            return &settings->values.deviceName;
        case Ximu3SettingsIndexSerialEnabled:
            return &settings->values.serialEnabled;
        case Ximu3SettingsIndexSerialBaudRate:
            return &settings->values.serialBaudRate;
        case Ximu3SettingsIndexSerialRtsCtsEnabled:
            return &settings->values.serialRtsCtsEnabled;
        case Ximu3SettingsIndexGyroscopeNotchFilterEnabled:
            return &settings->values.gyroscopeNotchFilterEnabled;
        case Ximu3SettingsIndexGyroscopeAntiAliasing:
            return &settings->values.gyroscopeAntiAliasing;
        case Ximu3SettingsIndexAccelerometerAntiAliasing:
            return &settings->values.accelerometerAntiAliasing;
        case Ximu3SettingsIndexSampleRate:
            return &settings->values.sampleRate;
        case Ximu3SettingsIndexAxesRemap:
            return &settings->values.axesRemap;
        case Ximu3SettingsIndexGyroscopeBiasCorrectionEnabled:
            return &settings->values.gyroscopeBiasCorrectionEnabled;
        case Ximu3SettingsIndexAhrsUpdateRateDivisor:
            return &settings->values.ahrsUpdateRateDivisor;
        case Ximu3SettingsIndexAhrsAxesConvention:
            return &settings->values.ahrsAxesConvention;
        case Ximu3SettingsIndexAhrsGain:
            return &settings->values.ahrsGain;
        case Ximu3SettingsIndexAhrsAccelerationRejection:
            return &settings->values.ahrsAccelerationRejection;
        case Ximu3SettingsIndexDataMessageMode:
            return &settings->values.dataMessageMode;
        case Ximu3SettingsIndexAhrsMessageType:
            return &settings->values.ahrsMessageType;
        case Ximu3SettingsIndexInertialMessageRateDivisor:
            return &settings->values.inertialMessageRateDivisor;
        case Ximu3SettingsIndexAhrsMessageRateDivisor:
            return &settings->values.ahrsMessageRateDivisor;
        case Ximu3SettingsIndexTemperatureMessageRateDivisor:
            return &settings->values.temperatureMessageRateDivisor;
        case Ximu3SettingsIndexUsbSendMode:
            return &settings->values.usbSendMode;
        case Ximu3SettingsIndexSerialSendMode:
            return &settings->values.serialSendMode;

    }
    return NULL; // avoid compiler warning
}

Metadata MetadataGet(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {
    const Metadata metadata = {
        .name = names[index],
        .key = keys[index],
        .value = GetValue(settings, index),
        .type = types[index],
        .size = sizes[index],
        .defaultValue = defaults[index],
        .preserved = preserveds[index],
        .readOnly = readOnlys[index],
        .applied = &settings->applied[index],
    };
    return metadata;
}
