// This file was generated by generate.py

#ifndef XIMU3_DEFINITIONS_H
#define XIMU3_DEFINITIONS_H

#include "Imu/Fusion/Fusion.h"
#include "Imu/Imu.h"
#include "Send/Send.h"
#include <stdbool.h>
#include <stdint.h>

#define XIMU3_READ_SIZE 2048

#define XIMU3_KEY_SIZE 64

#define XIMU3_VALUE_SIZE 512

#define XIMU3_OBJECT_SIZE 1024

#define XIMU3_MAX_KEY_LENGTH 35

#define XIMU3_NUMBER_OF_SETTINGS 29

#define XIMU3_MUX_HEADER_SIZE 2

typedef enum {
    Ximu3ResultOk,
    Ximu3ResultError,
} Ximu3Result;

typedef struct {
    char serialNumber[16];
    char hardwareVersion[32];
    char calibrationDate[32];
    FusionMatrix gyroscopeMisalignment;
    FusionVector gyroscopeSensitivity;
    FusionVector gyroscopeOffset;
    FusionMatrix accelerometerMisalignment;
    FusionVector accelerometerSensitivity;
    FusionVector accelerometerOffset;
    char firmwareVersion[32];
    char deviceName[32];
    bool serialEnabled;
    uint32_t serialBaudRate;
    bool serialRtsCtsEnabled;
    ImuAntiAliasing antiAliasing;
    ImuSampleRate sampleRate;
    FusionAxesAlignment axesAlignment;
    bool gyroscopeOffsetCorrectionEnabled;
    uint32_t ahrsUpdateRateDivisor;
    FusionConvention ahrsAxesConvention;
    float ahrsGain;
    float ahrsAccelerationRejection;
    bool binaryModeEnabled;
    SendAhrsMessageType ahrsMessageType;
    uint32_t inertialMessageRateDivisor;
    uint32_t ahrsMessageRateDivisor;
    uint32_t temperatureMessageRateDivisor;
    bool usbDataMessagesEnabled;
    bool serialDataMessagesEnabled;
} Ximu3SettingsValues;

typedef enum {
    Ximu3SettingsIndexSerialNumber,
    Ximu3SettingsIndexHardwareVersion,
    Ximu3SettingsIndexCalibrationDate,
    Ximu3SettingsIndexGyroscopeMisalignment,
    Ximu3SettingsIndexGyroscopeSensitivity,
    Ximu3SettingsIndexGyroscopeOffset,
    Ximu3SettingsIndexAccelerometerMisalignment,
    Ximu3SettingsIndexAccelerometerSensitivity,
    Ximu3SettingsIndexAccelerometerOffset,
    Ximu3SettingsIndexFirmwareVersion,
    Ximu3SettingsIndexDeviceName,
    Ximu3SettingsIndexSerialEnabled,
    Ximu3SettingsIndexSerialBaudRate,
    Ximu3SettingsIndexSerialRtsCtsEnabled,
    Ximu3SettingsIndexAntiAliasing,
    Ximu3SettingsIndexSampleRate,
    Ximu3SettingsIndexAxesAlignment,
    Ximu3SettingsIndexGyroscopeOffsetCorrectionEnabled,
    Ximu3SettingsIndexAhrsUpdateRateDivisor,
    Ximu3SettingsIndexAhrsAxesConvention,
    Ximu3SettingsIndexAhrsGain,
    Ximu3SettingsIndexAhrsAccelerationRejection,
    Ximu3SettingsIndexBinaryModeEnabled,
    Ximu3SettingsIndexAhrsMessageType,
    Ximu3SettingsIndexInertialMessageRateDivisor,
    Ximu3SettingsIndexAhrsMessageRateDivisor,
    Ximu3SettingsIndexTemperatureMessageRateDivisor,
    Ximu3SettingsIndexUsbDataMessagesEnabled,
    Ximu3SettingsIndexSerialDataMessagesEnabled,
} Ximu3SettingsIndex;

Ximu3Result Ximu3SettingsIndexFrom(Ximu3SettingsIndex * const index, const int integer);

#endif
