// This file was generated by generate.py

#ifndef XIMU3_DEFINITIONS_H
#define XIMU3_DEFINITIONS_H

#include <stdbool.h>
#include <stdint.h>

#define XIMU3_KEY_SIZE 64

#define XIMU3_VALUE_SIZE 512

#define XIMU3_OBJECT_SIZE 1024

#define XIMU3_MAX_KEY_LENGTH 22

#define XIMU3_NUMBER_OF_SETTINGS 9

typedef struct {
    char serialNumber[16];
    char calibrationDate[32];
    float offset;
    float sensitivity;
    char firmwareVersion[32];
    char deviceName[32];
    bool serialEnabled;
    uint32_t serialBaudRate;
    bool serialRtsCtsEnabled;
} Ximu3SettingsValues;

typedef enum {
    Ximu3SettingsIndexSerialNumber,
    Ximu3SettingsIndexCalibrationDate,
    Ximu3SettingsIndexOffset,
    Ximu3SettingsIndexSensitivity,
    Ximu3SettingsIndexFirmwareVersion,
    Ximu3SettingsIndexDeviceName,
    Ximu3SettingsIndexSerialEnabled,
    Ximu3SettingsIndexSerialBaudRate,
    Ximu3SettingsIndexSerialRtsCtsEnabled,
} Ximu3SettingsIndex;

#endif
